# Generated by Django 2.2.4 on 2019-09-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_model_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='model_user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='model_user',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='User name'),
        ),
    ]
